[package]
name = "wiktionary-en-download"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utilities = { path = "../utilities" }
anyhow = { workspace = true }
reqwest = { version = "0.12.22", features = ["stream"] }
futures-util = "0.3.31"
indicatif = { workspace = true }
tokio = { version = "1.47.1", features = ["full"] }
