[package]
name = "wiktionary-en-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = 'wiktionary-en-import'
path = "sonic-import/src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utilities = { path = "utilities" }
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.3"
indoc = "1.0"
colored = "2.1.0"
edit-distance="*"
textwrap="*"
wiktionary_entities = { version = "0.1.0", path = "wiktionary-entities" }
sonic-channel = { version = "1.1", features = ["ingest"] }
