[workspace]
resolver = "2"
members = ["crates/*", "tests"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
textwrap = "0.16.2"
edit-distance = "2.1.3"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
serde_json = "1.0"
