[workspace]
resolver = "2"
members = ["crates/*", "tests"]

[workspace.package]
name = "wiktionary-en-cli"
version = "0.1.0"
edition = "2021"

[workspace.features]
sonic = [ "wiktionary-en-identifier-index" ]

[workspace.dependencies]
anyhow = "1.0"
textwrap = "0.16.2"
edit-distance = "2.1.3"
