[package]
name = "wiktionary-en-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utilities = { path = "utilities" }
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.3"
indoc = "1.0"
colored = "1.0"
edit-distance="*"
textwrap="*"
sled = "0.34"
