[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DICTIONARY_DB_PATH_PLACEHOLDER = "${CARGO_MAKE_WORKING_DIRECTORY}/wiktionary-en-json-extract/wiktionary-{}.jsonl"
DICTIONARY_POLD_DB_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/wiktionary-en-polo-db/"
USE_SONIC_FEATURE = true

[tasks.install-wiktionary-en-cli]
workspace = false
command = "cargo"
condition = { env_true = [ "USE_SONIC_FEATURE" ] }
args = [
	"install", "--path", "crates/wiktionary-en-cli",
	"--features", "sonic"
]

[tasks.install-wiktionary-en-cli-no-sonic]
condition = { env_false = [ "USE_SONIC_FEATURE" ] }
workspace = false
command = "cargo"
args = ["install", "--path", "crates/wiktionary-en-cli"]

[tasks.install-wiktionary-en-import]
condition = { env_true = [ "USE_SONIC_FEATURE" ] }
workspace = false
command = "cargo"
args = [
	"install", "--path", "crates/wiktionary-en-import",
	"--features", "sonic"
]

[tasks.install-wiktionary-en-import-no-sonic]
condition = { env_false = [ "USE_SONIC_FEATURE" ] }
workspace = false
command = "cargo"
args = [ "install", "--path", "crates/wiktionary-en-import" ]


[tasks.sonic-host]
condition = { env_true = [ "USE_SONIC_FEATURE" ], env_not_set = [ "SONIC_HOST" ] }
env = { "SONIC_HOST" = "localhost:1491" }

[tasks.sonic-password]
condition = { env_true = [ "USE_SONIC_FEATURE" ], env_not_set = [ "SONIC_PASSWORD" ] }
env = { "SONIC_PASSWORD" = "SecretPassword" }

[tasks.install]
workspace = false
dependencies = [
	"sonic-host", "sonic-password",
	"install-wiktionary-en-cli", "install-wiktionary-en-import",
	"install-wiktionary-en-cli-no-sonic", "install-wiktionary-en-import-no-sonic"
]
