[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DICTIONARY_DB_PATH_PLACEHOLDER = "${CARGO_MAKE_WORKING_DIRECTORY}/wiktionary-en-json-extract/wiktionary-{}.json"

DICTIONARY_POLD_DB_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/wiktionary-en-polo-db/"

[tasks.install-wiktionary-en-cli]
workspace = false
command = "cargo"
args = [
	"install", "--path", "crates/wiktionary-en-cli",
	"--features", "sonic"
]

[tasks.install-wiktionary-en-import]
workspace = false
command = "cargo"
args = ["install", "--path", "crates/wiktionary-en-import"]

[tasks.install]
workspace = false
dependencies = ["install-wiktionary-en-cli", "install-wiktionary-en-import"]
