[package]
name = "utilities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textwrap="*"
serde_json = "1.0"
anyhow = {workspace = true}
serde = { version = "1.0" }
colored = "2.1.0"
minus = { version = "5.6.1", features = ["static_output", "search"] }
streaming-iterator = { version = "0.1.9" }
