[package]
name = "wiktionary-en-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
wiktionary_entities = { version = "0.1.0", path = "../wiktionary-entities" }
wiktionary-en-db = { path = "../wiktionary-en-db" }
utilities = { path = "../utilities" }
clap = { version = "3.0", features = ["derive"] }
anyhow = {workspace = true} 
serde = { version = "1.0", features = ["derive"] }
sled = "0.34"
colored = "2.1.0"
textwrap="*"
indoc = "1.0"
edit-distance="*"
