services:
  wiktionary_couchdb:
    image: docker.io/library/couchdb:3.5.2
    ports:
      - 5984:5984
    volumes:
      - ./couchdb-data:/opt/couchdb/data:Z
      - ./single-node.ini:/opt/couchdb/etc/local.d/single-node.ini:Z
    restart: always
    environment:
      COUCHDB_USER: ${COUCH_DB_USER}
      COUCHDB_PASSWORD: ${COUCH_DB_PASSWORD}

volumes:
  couchdb_data:
